spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/study/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      # 애플리케이션 실행시점에, 모든 테이블을 drop-create 한다
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
